
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/mydb"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dhinesh
      MONGO_INITDB_ROOT_PASSWORD: pandian
      MONGO_INITDB_DATABASE: dhinesh
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
