apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    # Choose a port in the range 30000-32767
  selector:
    app: day-4-express-db
