apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  express-k8s
  template:
    metadata:
      labels:
        app:  express-k8s
    spec:
      containers:
      - name:  express-k8s
        image: dhineshpandian/express-k8s:latest
        ports:
        - containerPort: 3000
